= Tools
jnorthr <james.northrop@orange>
v1.0
:icons: font

''''

IMPORTANT: Travis Build Status for Master Branch: image:https://img.shields.io/travis/jnorthr/Tools.svg[Build Status (Travis CI), link=https://travis-ci.org/jnorthr/Tools]

''''

== Purpose

A Gradle project for Groovy users who need utility code to identify a local directory. Clone includes gradle build tool wrapper and folder structure like maven/gradle so you don't need an installed gradle build tool.
 
.Pre-requisites
 . Working internet connection
 . Installed Git client to copy/clone this repo
 . Ability to use terminal console

.Steps  
 . Open terminal console
 . Change directory \( cd \) into target folder location
 . Run this command to create a folder and copy down all the pieces :

   git clone https://github.com/jnorthr/Tools.git

 . *cd Tools/*
 . *./gradlew* runs a series of defined tasks to build and test code samples
 . After prior step completes, examine *Tools/* folder to find the */build/* folder with test results

''''

NOTE: *.travis.yml* needed extra logic to be able to push to github repo and have Travis C/I testing work as expected.

''''
